export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOOKUP_SUCCESS = "LOOKUP_SUCCESS";
export const LOOKUP_FAILED = "LOOKUP_FAILED";

export const LOGOUT = "LOGOUT";
